test clinvarome lib:
  image: registry.gitlab.seq.one/devops/dockerfiles/python:3.7.9-docker-compose-migrate-htslib
  stage: test_tool
  script:
    - cd tools/clinvarome
    - poetry install
    - poetry run flake8
    - poetry run pytest -v
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - tools/clinvarome/**/*
  tags:
    - docker-executor
